### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Lucas86Bur** [hypothermic/FoscamViewer#3]
Hello, 
I have an issue when I lunch the jar on Ubuntu 18.04.1 , apparently the problem is my java version because JavaFX is not present in java version 11.
I am not quite sure if I need to had JavaFX or download an older version of Java, do you have any clue?

Here is my error on my terminal :

~/Downloads$ java -jar fscviewer-1.17-linux-64bit.jar
Error: Could not find or load main class nl.hypothermic.fscviewer.FoscamViewer
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
~/Downloads$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

Sorry if the solution is super obvious, I don't have a lot of experience yet :grimacing:

**Comment by hypothermic** [comment]
Hello, unfortunately this project is no longer maintained due to JavaFX being removed from the JDK in versions 11 and up. There's a workaround for this called OpenJFX, but I'm not interested in it because it isn't supported by Oracle.

The only way to run FoscamViewer is to use JDK 8 or 10, I'm afraid.

**Comment by Lucas86Bur** [comment]
Hello,
Well I tried switching my java version to 8 but I still have the same error :disappointed: ,
this time I only have the "Error" line and not the "Caused by" line, so maybe the JavaFX issue is solved.

Then I tried to compile the project myself using IntelliJ but with this method I get a "no manifest attribute" error when I launch the .jar 
Also I find it quite strange that I had no problem compiling with java 11 in IntelliJ but when I tried to compile with java 8 in IntelliJ I have an error saying "package javafx does not exist" 

Thanks a lot for you support.

**Comment by hypothermic** [comment]
Hello.

Which JDK distribution did you try with Java 8?
The project is only tested with Oracle JDK 8, and not with OpenJDK.

Please try using Oracle JDK to run the JAR file.

**Comment by Lucas86Bur** [comment]
It wasn't easy to install Oracle JDK 8 on Ubuntu, but it works !! thanks a lot for your support.
So it was implicit to use Oracle JDK 8 ? Because it wasn't my default version.

**Comment by hypothermic** [comment]
This is quite an old project (last update was fall 2018) and iirc Oracle JDK 8 was the default for Ubuntu back then. I could update it to OpenJFX but I wouldn't be able to test it because I sold my Foscam camera's last year.

**Comment by Lucas86Bur** [comment]
Ok, 
I am trying to connect a foscam that is not on my LAN, I tried to connect using the global IP of the network where the cam is, but I'm unable to connect,
 Have you already tried this ? is there something that should be modified on the remote network in order to accept or is it ok ?

**Comment by hypothermic** [comment]
I haven't tried connecting to WAN camera's, but it should work as long as FFmpeg can connect to it.
